name: AWS ECR API

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Docker Cache
              run: mkdir ~/ghcache

            - uses: actions/cache@v1
              with:
                  path: ~/ghcache
                  key: docker-cache.tar.gz
                  restore-keys: |
                      docker-cache.tar.gz

            - name: Docker Load Cache
              run: |
                if [[ -e ~/ghcache/docker-cache.tar.gz ]]; then
                    < ~/ghcache/docker-cache.tar.gz | gunzip | docker load
                fi

            - name: Docker Build API
              run: docker build -t api api/

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Docker Tag API
              run: docker tag api ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/batch:api-${GITHUB_SHA}

            - name: Docker Push API
              run: docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/batch:api-${GITHUB_SHA}

            - name: Docker Save API
              run: |
                mkdir ./ghcache
                docker save ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-1.amazonaws.com/batch:api-${GITHUB_SHA} | gzip > ./ghcache/docker-cache.tar.gz
